#!/usr/bin/env node
/* ==========================================================================
   Encrypts secrets.json into ../vault.js with a passphrase you choose.

     node tools/encrypt.js "your passphrase here"

   Output is AES-256-GCM ciphertext with a PBKDF2-SHA256 key (600k rounds).
   vault.js is safe to commit and publish; secrets.json is NOT and is
   gitignored. Anyone with the published URL can attempt an offline brute
   force against the ciphertext, so the passphrase must be a real one —
   four random words or better, not a date or a hotel name.
   ========================================================================== */

const fs = require('fs');
const path = require('path');
const { webcrypto } = require('crypto');
const { subtle } = webcrypto;
const rand = (n) => webcrypto.getRandomValues(new Uint8Array(n));

const ITERATIONS = 600_000;

async function main() {
  const pass = process.argv[2];
  if (!pass) {
    console.error('\n  Usage: node tools/encrypt.js "your passphrase"\n');
    process.exit(1);
  }
  if (pass.length < 12) {
    console.error('\n  Refusing: passphrase is under 12 characters.');
    console.error('  This ciphertext will be published. Use four random words or more.\n');
    process.exit(1);
  }

  const srcPath = path.join(__dirname, '..', 'secrets.json');
  if (!fs.existsSync(srcPath)) {
    console.error(`\n  No secrets.json found at ${srcPath}\n`);
    process.exit(1);
  }

  const plaintext = fs.readFileSync(srcPath, 'utf8');
  JSON.parse(plaintext); // fail loudly on malformed JSON before encrypting

  const salt = rand(16);
  const iv   = rand(12);

  const baseKey = await subtle.importKey(
    'raw', new TextEncoder().encode(pass), 'PBKDF2', false, ['deriveKey']
  );
  const key = await subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    baseKey,
    { name: 'AES-GCM', length: 256 },
    false, ['encrypt']
  );
  const ct = await subtle.encrypt(
    { name: 'AES-GCM', iv }, key, new TextEncoder().encode(plaintext)
  );

  const b64 = (buf) => Buffer.from(buf).toString('base64');
  const payload = {
    v: 1,
    kdf: { name: 'PBKDF2', hash: 'SHA-256', iterations: ITERATIONS },
    salt: b64(salt),
    iv: b64(iv),
    ct: b64(ct),
  };

  const out = `/* Generated by tools/encrypt.js — do not edit by hand.
   AES-256-GCM ciphertext. Useless without the passphrase. */
export const VAULT = ${JSON.stringify(payload, null, 2)};
`;

  const outPath = path.join(__dirname, '..', 'vault.js');
  fs.writeFileSync(outPath, out, 'utf8');

  console.log(`\n  Wrote ${outPath}`);
  console.log(`  ${plaintext.length} bytes plaintext → ${payload.ct.length} bytes base64 ciphertext`);
  console.log(`  PBKDF2-SHA256 @ ${ITERATIONS.toLocaleString()} rounds, AES-256-GCM\n`);
}

main().catch((err) => { console.error(err); process.exit(1); });
